CREATE TABLE Sheet1(--_========================= VARCHAR(10));
INSERT INTO Sheet1 (--_=========================) VALUES 
('-- UTILIZADORES'),
('-- ========================='),
('CREATE TABLE utilizadores ('),
('    utilizador_id SERIAL PRIMARY KEY,'),
('    nome_completo VARCHAR(200) NOT NULL,'),
('    email_contacto VARCHAR(200) UNIQUE NOT NULL,'),
('    telemovel VARCHAR(15),'),
('    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    estado_conta VARCHAR(20),'),
('    consentimentos JSONB,'),
('    idioma_pref VARCHAR(5),'),
('    opcoes JSONB'),
(');'),
('-- ========================='),
('-- AUTENTICAÇÃO'),
('-- ========================='),
('CREATE TABLE credenciais ('),
('    credencial_id SERIAL PRIMARY KEY,'),
('    utilizador_id INT UNIQUE NOT NULL,'),
('    login_nome VARCHAR(150) UNIQUE,'),
('    email_login VARCHAR(200),'),
('    password_hash TEXT NOT NULL,'),
('    metodo_login VARCHAR(50),'),
('    mfa_ativo BOOLEAN DEFAULT FALSE,'),
('    FOREIGN KEY (utilizador_id)'),
('    REFERENCES utilizadores(utilizador_id)'),
('    ON DELETE CASCADE'),
(');'),
('CREATE TABLE registos_login ('),
('    registo_id SERIAL PRIMARY KEY,'),
('    utilizador_id INT NOT NULL,'),
('    data_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    ip_acesso VARCHAR(50),'),
('    dispositivo TEXT,'),
('    FOREIGN KEY (utilizador_id)'),
('    REFERENCES utilizadores(utilizador_id)'),
('    ON DELETE CASCADE'),
(');'),
('-- ========================='),
('-- ORDENS (COMPRAS)'),
('-- ========================='),
('CREATE TABLE ordens ('),
('    ordem_id SERIAL PRIMARY KEY,'),
('    utilizador_id INT NOT NULL,'),
('    evento_ref INT,'),
('    total_bilhetes SMALLINT NOT NULL,'),
('    valor_final NUMERIC(9,2) NOT NULL,'),
('    desconto_aplicado NUMERIC(9,2),'),
('    estado_ordem VARCHAR(20),'),
('    FOREIGN KEY (utilizador_id)'),
('    REFERENCES utilizadores(utilizador_id)'),
(');'),
('-- ========================='),
('-- INGRESSOS (BILHETES)'),
('-- ========================='),
('CREATE TABLE ingressos ('),
('    ingresso_id SERIAL PRIMARY KEY,'),
('    ordem_id INT NOT NULL,'),
('    codigo_rfid VARCHAR(120) UNIQUE NOT NULL,'),
('    codigo_qr VARCHAR(120),'),
('    zona VARCHAR(40),'),
('    fila VARCHAR(5),'),
('    assento VARCHAR(5),'),
('    estado_ingresso VARCHAR(20),'),
('    emitido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    entrada_em TIMESTAMP,'),
('    FOREIGN KEY (ordem_id)'),
('    REFERENCES ordens(ordem_id)'),
('    ON DELETE CASCADE'),
(');'),
('-- ========================='),
('-- PAGAMENTOS'),
('-- ========================='),
('CREATE TABLE transacoes ('),
('    transacao_id SERIAL PRIMARY KEY,'),
('    ordem_id INT NOT NULL,'),
('    metodo_pagamento VARCHAR(50),'),
('    estado_pagamento VARCHAR(20),'),
('    referencia_gateway VARCHAR(255),'),
('    token_transacao TEXT,'),
('    ultimos_digitos CHAR(4),'),
('    moeda VARCHAR(10),'),
('    valor NUMERIC(9,2),'),
('    FOREIGN KEY (ordem_id)'),
('    REFERENCES ordens(ordem_id)'),
('    ON DELETE CASCADE'),
(');'),
('-- ========================='),
('-- PORTAIS (PORTAS)'),
('-- ========================='),
('CREATE TABLE portais ('),
('    portal_id SERIAL PRIMARY KEY,'),
('    descricao VARCHAR(80) NOT NULL UNIQUE'),
(');'),
('-- ========================='),
('-- VALIDAÇÕES (ENTRADAS)'),
('-- ========================='),
('CREATE TABLE registo_entradas ('),
('    registo_id SERIAL PRIMARY KEY,'),
('    ingresso_id INT NOT NULL,'),
('    portal_id INT NOT NULL,'),
('    momento_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    equipamento VARCHAR(100),'),
('    estado_validacao VARCHAR(30),'),
('    FOREIGN KEY (ingresso_id)'),
('    REFERENCES ingressos(ingresso_id)'),
('    ON DELETE CASCADE,'),
('    FOREIGN KEY (portal_id)'),
('    REFERENCES portais(portal_id)'),
(');'),
('-- ========================='),
('-- REEMBOLSOS'),
('-- ========================='),
('CREATE TABLE devolucoes ('),
('    devolucao_id SERIAL PRIMARY KEY,'),
('    transacao_id INT NOT NULL,'),
('    valor_devolvido NUMERIC(9,2),'),
('    motivo TEXT,'),
('    estado_devolucao VARCHAR(20),'),
('    data_processo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    referencia_original VARCHAR(255),'),
('    FOREIGN KEY (transacao_id)'),
('    REFERENCES transacoes(transacao_id)'),
(');'),
('-- ========================='),
('-- ÍNDICES (performance)'),
('-- ========================='),
('CREATE INDEX idx_ingressos_rfid ON ingressos(codigo_rfid);'),
('CREATE INDEX idx_registo_entradas_ingresso ON registo_entradas(ingresso_id);'),
('CREATE INDEX idx_registo_entradas_data ON registo_entradas(momento_leitura);'),
('CREATE INDEX idx_ordens_utilizador ON ordens(utilizador_id);');